# -*- coding: utf-8 -*-
"""task 7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rzgrYp4EveNjyxZYxam9rliCgNLu_xoS
"""

# STEP 1: SQLite database create cheddam and data insert cheddam
import sqlite3

# sales_data.db ane database create avutundi
conn = sqlite3.connect('sales_data.db')
cursor = conn.cursor()

# sales ane table create cheddam
cursor.execute('''
CREATE TABLE IF NOT EXISTS sales (
    id INTEGER PRIMARY KEY,
    product TEXT,
    quantity INTEGER,
    price REAL
)
''')

# Sample data insert cheddam (manam dataset ni create chesthunnaam)
sample_data = [
    ('Apples', 10, 20.0),
    ('Bananas', 15, 10.0),
    ('Apples', 5, 20.0),
    ('Oranges', 7, 25.0),
    ('Bananas', 10, 10.0)
]

cursor.executemany('INSERT INTO sales (product, quantity, price) VALUES (?, ?, ?)', sample_data)
conn.commit()
conn.close()

# STEP 2: Data read cheddam, query cheddam, graph display cheddam
import pandas as pd
import matplotlib.pyplot as plt

# Database connect avutondi
conn = sqlite3.connect('sales_data.db')

# SQL query run cheyyadam (total quantity, revenue calculate cheyyadam)
query = '''
SELECT
    product,
    SUM(quantity) AS total_qty,
    SUM(quantity * price) AS revenue
FROM sales
GROUP BY product
'''

# Pandas tho result fetch cheddam
df = pd.read_sql_query(query, conn)
conn.close()

# Result print cheddam
print("Sales Summary:")
print(df)

# Revenue graph bar chart lo chupiddam
df.plot(kind='bar', x='product', y='revenue', title='Revenue per Product', legend=False)
plt.ylabel('Revenue')
plt.tight_layout()
plt.show()